# Constant to re-use within the yaml config file
define: &batchSize 50
spring:
  config:
    activate:
      on-profile: "test"
    #   Configuration of Data Source
    persistence:
      postgres:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/bank_microservice_db
        username: postgres
        password: test
        schema: public
        liquibase:
          changelog: "classpath:/db/changelog/db.changelog-postgres-master.yaml"
        packageToScan: com.github.pavelvashkevich.bankmicroservice.model.postgres
      cassandra:
        contactPoints: localhost
        localDatacenter: datacenter1
        keyspaceName: spring_currency_exchange_cassandra
  #  Configuration of Hibernate
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: *batchSize
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        show_sql: true
        # for debug purpose only
        format_sql: true
        order_inserts: true
        order_updates: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
# Configuration of third-party API
twelvdate:
  apiKey: 3c9fcbdeca124aec8f4dec9bcb651818
  maxConnectionRetryAttempts: 5
  minDelayBetweenAttempts: 500
  maxDelayBetweenAttempts: 1000
# Configuration of daily currency rate updater
rateUpdater:
  rate:
    previous:
      cronExpression: "0 0 * * * ?"
    close:
      cronExpression: "0 0 17 * * ?"
      timezone: "America/New_York"
# Configuration of monthly limit updater
limitUpdater:
  batchSize: *batchSize
  defaultLimit:
    cronExpression: "0 0 * * * ?"
# Others
limit:
  defaultCurrency: "USD"
